source 'https://rubygems.org'

gem 'avro_turf'
gem 'bitstring'
gem 'certifi'
gem 'dotenv'
gem 'faraday'
gem 'grpc'
gem 'grpc-tools'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'ruby-limiter'
